export const ROOMS = [
  {
    id: 'tinyagi',
    name: 'TinyAGI',
    roomLabel: 'Command Center',
    accent: '#00e5ff',
    wall: '#050e1c',
    floor: '#091828',
    botPalette: { hair: '#00e5ff', skin: '#e8b87a', shirt: '#004d68' },
    furniture: 'command',
  },
  {
    id: 'market-analyst',
    name: 'Market Analyst',
    roomLabel: 'Observatory',
    accent: '#ffd700',
    wall: '#140e04',
    floor: '#201508',
    botPalette: { hair: '#ffd700', skin: '#d4956a', shirt: '#584000' },
    furniture: 'observatory',
  },
  {
    id: 'notion-creator',
    name: 'Notion Creator',
    roomLabel: 'Creative Studio',
    accent: '#ff66cc',
    wall: '#160a16',
    floor: '#220e22',
    botPalette: { hair: '#ff66cc', skin: '#e8b87a', shirt: '#5c0e5c' },
    furniture: 'studio',
  },
  {
    id: 'finance-creator',
    name: 'Finance Creator',
    roomLabel: 'Trading Floor',
    accent: '#44ff88',
    wall: '#051208',
    floor: '#0a1e10',
    botPalette: { hair: '#44ff88', skin: '#e8b87a', shirt: '#145635' },
    furniture: 'trading',
  },
  {
    id: 'business-creator',
    name: 'Business Creator',
    roomLabel: 'Boardroom',
    accent: '#cc88ff',
    wall: '#0e0816',
    floor: '#180e24',
    botPalette: { hair: '#cc88ff', skin: '#c09060', shirt: '#481870' },
    furniture: 'boardroom',
  },
  {
    id: 'copywriter',
    name: 'Copywriter',
    roomLabel: "Writer's Den",
    accent: '#ff9944',
    wall: '#140a04',
    floor: '#201408',
    botPalette: { hair: '#ff9944', skin: '#e8b87a', shirt: '#662e00' },
    furniture: 'den',
  },
  {
    id: 'publisher',
    name: 'Publisher',
    roomLabel: 'Print Shop',
    accent: '#44aaff',
    wall: '#050c18',
    floor: '#091220',
    botPalette: { hair: '#44aaff', skin: '#daa06a', shirt: '#163860' },
    furniture: 'printshop',
  },
  {
    id: 'analytics',
    name: 'Analytics',
    roomLabel: 'Server Room',
    accent: '#88ff44',
    wall: '#060c04',
    floor: '#0c1808',
    botPalette: { hair: '#88ff44', skin: '#e8b87a', shirt: '#264810' },
    furniture: 'server',
  },
]

export const ROOM_MAP = Object.fromEntries(ROOMS.map(r => [r.id, r]))
